######################################################################
# Automatically generated by qmake (2.00a) Thu May 4 12:25:15 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += ../../include ../../src .
LIBS += -L../../lib -lkdchart

# Input
HEADERS += CoordinatePlane.h BarDiagram.h
SOURCES += CoordinatePlane.cpp BarDiagram.cpp main.cpp
