######################################################################
# Automatically generated by qmake (2.00a) Sun May 7 08:50:26 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AlternatingColumnsProxyModel.h
SOURCES += AlternatingColumnsProxyModel.cpp main.cpp
