#ifndef KDCHARTSERIALIZER_EXPORT_H
#define KDCHARTSERIALIZER_EXPORT_H

#include <qglobal.h>

# ifdef KDCHARTSERIALIZER_STATICLIB
#  undef KDCHARTSERIALIZER_SHAREDLIB
#  define KDCHARTSERIALIZER_EXPORT
# else
#  ifdef KDCHART_BUILD_KDCHARTSERIALIZER_LIB
#   define KDCHARTSERIALIZER_EXPORT Q_DECL_EXPORT
#  else
#   define KDCHARTSERIALIZER_EXPORT Q_DECL_IMPORT
#  endif
# endif

#endif // KDCHARTSERIALIZER_EXPORT_H
