include (../variables.pri)

QT += svg

staticlib {
  DEFINES += KDCHARTSERIALIZER_STATICLIB
} else {
  DEFINES += KDCHARTSERIALIZER_SHAREDLIB
  win32 {
    DLLDESTDIR = $$PWD/bin
    CONFIG += dll
  }
}

DEFINES -= QT_NO_CAST_TO_ASCII QBA_NO_CAST_TO_VOID QBA_NO_CAST_TO_ASCII QT_NO_CAST_FROM_ASCII

