
SHOWINFO:
	@echo ""
	@echo ""
	@echo "========================================================="
	@echo ""
	@echo "  This file is part of the library KDABLibFakes,"
	@echo "  used internally for compiling and building the"
	@echo "  projects of Klaraelvdalens Datakonsult AB."
	@echo "  (visit http://www.kdab.net for information)"
	@echo ""
	@echo "  KDABLibFakes is matter of change without notification!"
	@echo ""
	@echo "  Do *not* include this library into your own projects!"
	@echo ""
	@echo "========================================================="
	@echo ""
	@echo ""



all:       SHOWINFO

first:     SHOWINFO

dist:      SHOWINFO

clean:     SHOWINFO

distclean: SHOWINFO

install:   SHOWINFO

uninstall: SHOWINFO
