# SPDX-FileCopyrightText: 2023 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: MIT

name: CI Nightly

on:
  workflow_dispatch:
  schedule:
  - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        config:
          - name: clang-tidy
            cmake_arg: '-DCMAKE_CXX_CLANG_TIDY=clang-tidy'
            qt_version: 6.9.0

          - name: clazy
            cmake_arg: '-DCMAKE_CXX_COMPILER=clazy'
            qt_version: 6.9.0
            apt_pgks:
              - clazy
              - cppcheck

    steps:
      - name: Install Qt ${{ matrix.config.qt_version }} with options and default aqtversion
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.config.qt_version }}
          cache: true

      - name: Install ninja-build tool (must be after Qt due PATH changes)
        uses: turtlesec-no/get-ninja@main

      - name: Install dependencies on Ubuntu (${{ join(matrix.config.apt_pgks, ' ') }})
        if: ${{ runner.os == 'Linux' && matrix.config.apt_pgks }}
        run: |
          sudo apt update -qq
          echo ${{ join(matrix.config.apt_pgks, ' ') }} | xargs sudo apt install -y
      - uses: actions/checkout@v4
        #with:
          #ref: '2.0' # schedule.cron do not allow branch setting

      - name: Configure project
        run: cmake --preset ${{ matrix.config.name }}

      - name: Build Project
        run: cmake --build ./build/${{ matrix.config.name }} --preset ${{ matrix.config.name }}

      - name: Run cppcheck
        if: ${{ matrix.config.name == 'clazy' }}
        run: cmake --build ./build/${{ matrix.config.name }} --target cppcheck
